#!/usr/bin/env bash

REPOSITORY=article-rec-training-job
DOCKER_OPTS=$(cat <<END_HEREDOC
    -v $HOME/.aws/credentials:/root/.aws/credentials:ro \
    -v $(pwd):/app \
    -e STAGE=local
END_HEREDOC
)

#@cdk
#+Run cdk.
task-cdk() {
    (cd cdk && npx cdk $@)
}

#@build
#+Build docker image.
task-build() {
    docker build . -t $REPOSITORY
}

#@run
#+Run docker container.
task-run() {
    docker run $DOCKER_OPTS -it $REPOSITORY "$@"
}

#@test
#+Run tests.
task-test() {
    docker run $DOCKER_OPTS $REPOSITORY py.test tests
}

#@backfill
#+Run backfill command in docker container.
task-backfill() {
    docker run $DOCKER_OPTS -it $REPOSITORY python /app/scripts/backfill_task.py $@
}

#@article-backfill
#+Run article backfill command in docker container.
task-article-backfill() {
    docker run $DOCKER_OPTS -it $REPOSITORY python /app/scripts/article_backfill.py $@
}